#! /Users/pl6/homebrew/bin/python
# ~/scripts/location_counter_v2.py table_of_samples.txt <country or city> <outprefix>

## Takes table of isolates generated by ~/scripts/genome_contribution_checker.py
## Takes level of location
## Outputs counts table with Location, Lat, Long, and counts for: WTSI or Other source, (Yam or Vic)

import re, sys
from geopy import geocoders
from collections import defaultdict

taxa_file = sys.argv[1]
level = sys.argv[2]
outprefix = sys.argv[3]

my_api_key = 'AIzaSyBwyuFNTVmW8aQQn8blRQ-t_w1srY1hjPU'
gn = geocoders.GoogleV3(my_api_key)
#pathway='/Users/pl6/Desktop/Projects'
pathway='/Users/pclangat/Documents/Professional/OldProjects'
loc_file = '%s/2-FluB/0-alignments_2015-08-25/17-Maps_of_samples/2-data/city_latlong_summary.txt' % pathway
outfh = open("%s_location_summary.txt" % outprefix, 'w')
locs_dict = defaultdict(dict)
locs_coords = {}
loc_count = 0
types = ['wtsi-yam', 'other-yam', 'wtsi-vic', 'other-vic']
geolocations = {}

## Get current locations and put into dictionary
with open(loc_file, 'r') as lfh:
	next(lfh)
	for line in lfh:
		line = line.strip()
		loc = (line.split('\t')[0]).lower()
		loc = re.sub(' ', '', loc)
		lat = line.split('\t')[1]
		lon = line.split('\t')[2]
		geolocations[loc] = (lat,lon)
		
with open(taxa_file, 'r') as tfh:
	next(tfh)
	for line in tfh:
		line = line.strip()
		strain, date_plain, date_dec, date_prec, region, country, gen_loc, city, source, id, lineage = line.split('\t')
		## Revise input
		country = re.sub('-', '', country)
		city = re.sub('-', '', city)
		(lat,lng) = (0,0)

		if 'WTSI' in source:
			source = 'wtsi'
		else:
			source = 'other'
		
		type = '%s-%s' % (source,lineage)
		
		##Check to see if anything's up with output
		print city + "\t" + country + "\t" + type
		
		if level == 'country':
			location = country
		elif level == 'city':
			location = city
		else:
			print "Error: do you want by 'country' or by 'city?'"
		
		if location.lower() in geolocations:
			(lat,lng) = geolocations[location.lower()]
			print "good"
		else:
			geoplace, (lat,lng) = gn.geocode(location)
		
		## Count the location and type	
		if location not in locs_dict:
			for t in types:
				locs_dict[location][t] = 0
			locs_coords[location] = (lat,lng)
			loc_count += 1
		locs_dict[location][type] += 1	

outfh.write("Location\tLat\tLong\twtsi-yam\tother-yam\twtsi-vic\tother-vic\n")
for location in sorted(locs_dict):
	lat = locs_coords[location][0]
	lng = locs_coords[location][1]
	outfh.write("%s\t%s\t%s" % (location, lat, lng))
	for t in types:
		outfh.write("\t%s" % locs_dict[location][t])
	outfh.write("\n")

print("%s %s locations counted" % (loc_count, level))
outfh.close()