### Input: a master list of genotypes (generated by genotypes_builder_v2.0.py) and desired segment MCCT
### Output: time-resolved tree, coloured branches for that segment with genotype blocks
### Colours: UND = grey, '' = white, pre-set for clades of interest

## Updating installation of ggtree and ggplot2
#source("https://bioconductor.org/biocLite.R")
#biocLite("BiocUpgrade")
#biocLite("ggtree")
#biocLite("ggplot2")
#biocLite("rvcheck")

## Setup
library("ggplot2")
library("ggtree")
library("grid")
library("RColorBrewer")
library("ape")
#library("rvcheck")
#rvcheck::check_bioc("ggtree")

## Examples to test
#file <- system.file("extdata/BEAST", "beast_mcc.tree", package="ggtree")
#beast <- read.beast(file)
#beast
#x <- read.beast("/Users/pl6/Software_downloaded/FigTree_v1.4.2/influenza.tree")

## Read in beast files
file_path <- "/Users/pl6/Desktop/Projects/2-FluB/0-alignments_2015-08-25/14-Broad_genotypes/9-Major_clades_2016-06-26/3-All_trees/plot_yam.HA.mcc.tree"
beast <- read.beast(file_path)
beast

## Read in genotype files
genotype_file <- "/Users/pclangat/Documents/Professional/OldProjects/2-FluB/0-alignments_2015-08-25/14-Broad_genotypes/9-Major_clades_2016-06-26/3-All_trees/genotypes_fluB_reduced.txt"
#genotype_file <- "/Users/pl6/Desktop/Projects/2-FluB/0-alignments_2015-08-25/14-Broad_genotypes/9-Major_clades_2016-06-26/3-All_trees/genotypes_fluB_NAvic.txt"
#genotype_file <- "/Users/pl6/Desktop/Projects/2-FluB/0-alignments_2015-08-25/14-Broad_genotypes/9-Major_clades_2016-06-26/3-All_trees/genotypes_fluB_PB1yam.txt"

genotype <- read.table(genotype_file, sep="\t", stringsAsFactors = F)

## Set specifics for that segment tree
prefix <- "Victoria NA"

#yamHA
#MRSD <- "2015-06-21"

#yamPB1
#MRSD <- "2015-06-02"

#vicHA
#MRSD <- "2015-04-30"

#vicNA
MRSD <- "2015-06-08"

vals <- unique(unlist(genotype))
vals <- vals[vals != ""] 
vals <- sort(vals[!is.na(vals)],decreasing=FALSE)
n <- length(vals)
vals

### Setup colours
## Scheme 1. ggplot colour schemce
#gg_color_hue <- function(n) {
#  hues = seq(15, 375, length=n+1)
#  hcl(h=hues, l=65, c=100)[1:n]
#}
#cols = gg_color_hue(n)

## Scheme 2. Colour brewer palette
#cols <- brewer.pal(12, "Paired")

## Scheme 3. Divy up a colour palette
#cols <- colorRampPalette(brewer.pal(12, "Spectral"))(20)

## Scheme 4. Custom
#cols <- c("#89A24C", "#9C4C9C", "#4173BA", "#DA5F5C")
paired <- brewer.pal(12,"Paired")
paired
#cols <- c("#32659f", "#D2C161", "#9D7546", "#7571B4", "#006400", "#89A24C", "#EA9145", "#92c4de", "#444444", "#be2f4b", "#EE96AD", "#D6D6D6")
cols <- c("#32659f", "#D2C161", "#006400", "#9D7546", "#7571B4", "#89A24C", "#EA9145", "#92c4de", "#444444", "#be2f4b", "#EE96AD", "#D6D6D6")

## from paired
#cols <- c("#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A", "#FFFF99", "#B15928")
#cols <- c("#1F78B4", "#FFFF99", "#B2DF8A", "#6A3D9A", "#CAB2D6", "#33A02C", "#FDBF6F", "#A6CEE3", "#FF7F00", "#E31A1C", "#FB9A99", "#B15928")

## Assign names to colours
names(cols) <- vals
#names(cols) <- c("B/Massachusetts/2/2012","B/NewYork/1238/2010","B/Wisconsin/1/2010","B/Florida/4/2006","B/Florida/7/2004","B/Shanghai/361/2002","B/Yamanashi/166/1998","B/Harbin/7/1994","B/Dakar/10/2012","B/Cambodia/30/2011","B/Odessa/3886/2010","B/Brisbane/60/2008","B/Victoria/304/2006","B/Malaysia/2506/2004","B/Brisbane/32/2002","B/HongKong/330/2001","B/Shangdong/7/1997","UN")
cols
cols[n] <- "#D6D6D6"

#Show BEAST MCCT with Genotypes
p <- ggtree(beast,  mrsd=MRSD, aes(color=HA)) + scale_color_manual(na.value="#D6D6D6",values=cols) + theme_tree2() + ggtitle(prefix) + theme(plot.title = element_text(hjust = 0)) + geom_point2(aes(colour=HA, subset=!is.na(as.numeric(posterior)) & posterior>0.7), size=1) #+ geom_text(aes(x=branch, label=posterior, vjust=-.5, size=3)) 
#p <- ggtree(beast,  mrsd=MRSD, aes(color=NAx)) + scale_color_manual(na.value="#D6D6D6",values=cols) + theme_tree2() + ggtitle(prefix) + theme(plot.title = element_text(hjust = 0)) + geom_point2(aes(colour=NAx, subset=!is.na(as.numeric(posterior)) & posterior>0.7), size=1) #+ geom_text(aes(x=branch, label=posterior, vjust=-.5, size=3)) 
#p <- ggtree(beast,  mrsd=MRSD, aes(color=PB1)) + scale_color_manual(na.value="#D6D6D6",values=cols) + theme_tree2() + ggtitle(prefix) + theme(plot.title = element_text(hjust = 0)) + geom_point2(aes(colour=PB1, subset=!is.na(as.numeric(posterior)) & posterior>0.7), size=1) #+ geom_text(aes(x=branch, label=posterior, vjust=-.5, size=3)) 

pp <- (p + scale_y_continuous(expand=c(0, 0.3))) %>%
  gheatmap(genotype, offset=0.5, width=0.5, colnames=FALSE) %>%
  scale_x_ggtree() + scale_fill_manual(values=cols)  #+ scale_x_continuous(limits=c(1985,2027),breaks=scales::pretty_breaks(10)) 
pp #+ theme(legend.position="none")
